version: '3'
services:
  database:
    image: postgres
    env_file: 
      - database.env
    volumes:
      - $HOME/docker/crap/database/:/var/lib/postgresql/data/
  express:
    build: ./server
    depends_on: 
      - database
    ports:
      - 3000:3000
    command: npm start
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: 'postgres://POSTGRES_USER:POSTGRES_PASSWORD@postgres:5432/POSTGRES_DB'
    volumes: 
      - $HOME/docker/crap/express:/app/data